#!/usr/bin/env python

from optparse import OptionParser

def main():
    usage = "usage: %prog [options]"
    parser = OptionParser(usage)
    parser.add_option("-d", "--debug",help="Debug mode",
                      action="store_true")
    parser.add_option("-a", "--all", help='Generate swagger API definition for all nimbula API', action="store_true", dest="all")
    (options, args) = parser.parse_args()
    if len(args) != 0:
        parser.error("Incorrect number of arguments")
    if options.debug:
        print "In Debug mode"
    if options.all:
        print "In All mode"

if __name__ == "__main__":
    main()
